### ISSUE TITLE
[ERROR] Java language support requires Java 8

### ISSUE THREAD

**Issue by linfx7** [georgewfraser/vscode-javac#8] opened 2016-06-02 11:13 UTC
Encontered error message while opening java files. And it didn't work.

Here is the full error message:
> Java language support requires Java 8 (using c:\Program Files\Java\jdk1.8.0_92\bin\java.exe)

I'm using Windows 10 x64 with jdk 1.8. "c:\Program Files\Java\jdk1.8.0_92\" is the root directory of jdk.

**Comment by georgewfraser** [comment] 2016-06-02 23:39
Can you show me the output when you run

> java -version

in a terminal?

**Comment by linfx7** [comment] 2016-06-03 01:11
`java -version`
> java version "1.8.0_92"
> Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
> Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

`javac -version`
> javac 1.8.0_92

**Comment by semornas** [comment] 2016-06-03 17:12
Hi,
Same issue on my computer (Windows 10 x64)
`java -version`
> java version "1.8.0_91"
> Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
> Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

**Comment by ecmel** [comment] 2016-06-04 18:19
Sam issue, VS Code version 1.1.1

**Comment by georgewfraser** [comment] 2016-06-05 19:02
Fixed with v0.0.14

**Closed by georgewfraser** 2016-06-05 19:02 UTC

**Comment by SimpleCookie** [comment] 2018-02-11 12:21
Actually the issue is still there. Just tried with ´version 0.18.1´
